[package]
name = "shippable"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/BlackspireAudio/rust-workshop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
